# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the codecov branch
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    steps:
      - name: Test
        uses: actions/checkout@v1
        
      - name: AWS S3 Github Action
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile jenkins-automated-test
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile jenkins-automated-test
          aws \
            --profile jenkins-automated-test \
            s3api get-object \
            --bucket amazon-chime-sdk-ios-internal \
            --key master/media/latest/AmazonChimeSDKMedia.tar.gz \
            AmazonChimeSDKMedia.tar.gz
          tar -xzf AmazonChimeSDKMedia.tar.gz
          cp -R ./AmazonChimeSDKMedia.framework ./AmazonChimeSDK
 #         cd ./AmazonChimeSDK
 #         mockingbird download starter-pack
    #      mockingbird install --sources AmazonChimeSDK --target AmazonChimeSDKTests
          
          
#         uses: keithweaver/aws-s3-github-action@v1.0.0
#         with:
#           command: cp
#           source: ./master/media/latest/AmazonChimeSDKMedia.tar.gz
#           destination: ./AmazonChimeSDKMedia.tar.gz
#           aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}

      
        
#       - name: Install Dependencies
#         run: |
#           cd AmazonChimeSDK
#           pod install --repo-update
#         shell: bash
        
#       - name: Mockingbird
#         run: which mockingbird
#         shell: bash
        
      - name: Build and Test
        working-directory: ./AmazonChimeSDK
        run: |
         # export PATH=$PATH:/usr/local/bin
          xcodebuild build -project AmazonChimeSDK.xcodeproj -scheme AmazonChimeSDK -destination 'platform=iOS Simulator,name=iPhone 11'
      - name: mockingbird
        run:
          which mockingbird
 #         xcodebuild test -project AmazonChimeSDK.xcodeproj -scheme AmazonChimeSDK -destination 'platform=iOS Simulator,name=iPhone 11' -enableCodeCoverage YES build test
  #        mockingbird download starter-pack
  #        mockingbird install --sources AmazonChimeSDK --target AmazonChimeSDKPodsTests
   #       xcodebuild test -workspace 'AmazonChimeSDK.xcworkspace' -scheme AmazonChimeSDKPods -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.2' -enableCodeCoverage YES 
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1
